version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  flask:
    container_name: shop_app
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    image: shop_backend_local_flask
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.envs/.local/.flask
      - ./.envs/.local/.postgres
    ports:
      - "5000:5000"

  postgres:
      build:
        context: .
        dockerfile: ./compose/production/postgres/Dockerfile
      image: shop_backend_production_postgres
      container_name: shop_database
      volumes:
        - local_postgres_data:/var/lib/postgresql/data
        - local_postgres_data_backups:/backups
      env_file:
        - ./.envs/.local/.postgres
      command:
        - "postgres"
        - "-c"
        - "log_statement=all"
      ports:
        - "5432:5432"